//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem1.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BuildCompanyEntities : DbContext
    {
        public static BuildCompanyEntities context;

        public static BuildCompanyEntities GetContext()
        {
            if (context == null)
                context = new BuildCompanyEntities();
            return context;
        }

        public BuildCompanyEntities()
            : base("name=BuildCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<materialType> materialType { get; set; }
        public virtual DbSet<partners> partners { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<requests> requests { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<typeOfPartner> typeOfPartner { get; set; }
        public virtual DbSet<typeOfProduct> typeOfProduct { get; set; }
    }
}
