//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class materialType
    {
        public int materialType_id { get; set; }
        public int materailType { get; set; }
        public double percentOfFail { get; set; }
    
        public virtual typeOfProduct typeOfProduct { get; set; }
    }
}
