//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partners()
        {
            this.requests = new HashSet<requests>();
        }
    
        public int partner_id { get; set; }
        public int typeOfPartner_id { get; set; }
        public string nameOfPartner { get; set; }
        public string directorName { get; set; }
        public string mailOfPartner { get; set; }
        public string phoneOfPartner { get; set; }
        public string addressOfPartner { get; set; }
        public string INN { get; set; }
        public int rate { get; set; }
    
        public virtual typeOfPartner typeOfPartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requests> requests { get; set; }
    }
}
