//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class requests
    {
        public int request_id { get; set; }
        public int product_id { get; set; }
        public int partner_id { get; set; }
        public int amountOfProduct { get; set; }
    
        public virtual partners partners { get; set; }
        public virtual products products { get; set; }
    }
}
